# -*- coding: utf-8 -*-

from scrapy import Item,Field

class PositiondetailsItem(Item):
    positionName = Field()
    city = Field()
    companyName = Field()
    companySize = Field()
    positionType = Field()
    salaryMax = Field()
    salaryMin = Field()
    workYear = Field()
    keyword = Field()
    formatCreatetime = Field()
    companyId = Field()
    link = Field()

    # positionName = Field()
    # company = Field()
    # city = Field()
    # experience = Field()
    # positionType = Field()
    # salary = Field()
    # description = Field()
    # link = Field()
    # publishedTime = Field()

    # kd = scrapy.Field()
    # title = scrapy.Field()
    # description = scrapy.Field()
    # tag = scrapy.Field()
    # company = scrapy.Field()
    # city = scrapy.Field()
    # salary = scrapy.Field()
    # experience = scrapy.Field()
    # education = scrapy.Field()
    # url = scrapy.Field()
    # address = scrapy.Field()
    # industry = scrapy.Field()
    # scale = scrapy.Field()
    # phase = scrapy.Field()
    # published = scrapy.Field()
